# Generated by Django 3.1.2 on 2020-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fellow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
