# Generated by Django 3.1.2 on 2020-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201008_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End time: (HH:MM)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start time: (HH:MM)'),
        ),
    ]
