# Generated by Django 3.1.2 on 2020-10-08 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201008_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date: (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date: (yyyy-mm-dd)'),
        ),
    ]
